# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CollectionViewSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'SVProgressHUD'
   	pod 'SDWebImage', '~> 4.0'
   	pod 'UIScrollView-InfiniteScroll', '~> 1.1.0'
  # Pods for CollectionViewSample

  target 'CollectionViewSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CollectionViewSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
